### ISSUE TITLE
Either `Account` is not found, or there might be a problem related to a limitation of Scala compile time reflection

### ISSUE THREAD

**Issue by ShahOdin** [DCI/scaladci-demo#1]
![screen shot 2017-06-19 at 17 04 04](https://user-images.githubusercontent.com/13497500/27294434-7986ed68-5511-11e7-892a-523cbd6a2199.png)

**Comment by marcgrue** [comment]
Apparently the Data classes can't compile if they are in the same scope as the @Context-annotated class. I must have forgot to test the sample example last time. The simple solution is to move the Data classes out of Context-scope - or one can add curly braces around the Context-annotated class to bring it into its own scope. The example is now updated and should work. Thanks for reporting!
